<?php

declare(strict_types=1);

namespace App\Support;

final class SetupInstructions
{
    /**
     * @return list<array{title: string, body: string, code: string|null}>
     */
    public function steps(): array
    {
        return [
            [
                'title' => 'Configure the permanent domain first',
                'body' => 'Configure a permanent custom domain on the provisioned Laravel Cloud installation before building either app. Telltale and Scalpels never provision this domain, and a URL shipped inside an app cannot be changed for that build.',
                'code' => null,
            ],
            [
                'title' => 'Create the app',
                'body' => 'Create an app in the Telltale package UI and copy its one-time ingest value when it appears. Telltale stores only its hash and cannot show the value again.',
                'code' => null,
            ],
            [
                'title' => 'Install the client',
                'body' => 'Run this command in the NativePHP application:',
                'code' => 'composer require artisan-build/telltale-client',
            ],
            [
                'title' => 'Set the build environment',
                'body' => 'Set both values in every mobile and desktop build environment. Use the permanent custom-domain URL and the one-time ingest value; do not rename TELLTALE_INGEST to a *_KEY, *_TOKEN, or *_SECRET variable.',
                'code' => "TELLTALE_URL=https://telltale.example.com\nTELLTALE_INGEST=tti_<one-time-value>",
            ],
            [
                'title' => 'Declare the data use',
                'body' => 'Add the PrivacyInfo.xcprivacy manifest and complete the App Store privacy-label and Google Play data-safety declarations before release. Review the platform data reference for the exact v1 capture boundaries.',
                'code' => null,
            ],
        ];
    }

    public function automationBoundary(): string
    {
        return 'Scalpels ends after provisioning Telltale and presenting these instructions. There is no connect flow, repository mutation, environment mutation, credential injection, or automated client wiring now or later.';
    }

    public function v1LimitSummary(): string
    {
        return 'Telltale v1 does not capture native crashes, OOM failures, ANRs, Electron Crashpad, or SuperNative screen exceptions. It adds no lifecycle signals and does not upload in the background on mobile. AsyncTask failure capture is a documented NativePHP request, not a framework workaround.';
    }

    /** @return array<string, string> */
    public function artifacts(): array
    {
        return [
            'docs/setup.md' => $this->setupMarkdown(),
            'docs/scalpels-handoff.md' => $this->scalpelsHandoffMarkdown(),
        ];
    }

    public function setupMarkdown(): string
    {
        return $this->markdown(
            'Telltale Setup',
            'Complete these steps in order. The domain must be permanent before either app is built.',
        );
    }

    public function scalpelsHandoffMarkdown(): string
    {
        return $this->markdown(
            'Telltale Post-Provision Handoff',
            'Scalpels has provisioned the Telltale server. It presents the following instructions without changing the developer\'s application or environment.',
        );
    }

    private function markdown(string $title, string $introduction): string
    {
        $lines = [
            "# {$title}",
            '',
            '<!-- Generated by `php artisan telltale:generate-docs --local`. Do not edit by hand. -->',
            '',
            $introduction,
            '',
        ];

        foreach ($this->steps() as $index => $step) {
            $lines[] = ($index + 1).". **{$step['title']}.** {$step['body']}";

            if ($step['code'] !== null) {
                $lines[] = '';
                $lines[] = '   ```dotenv';

                foreach (explode("\n", $step['code']) as $codeLine) {
                    $lines[] = "   {$codeLine}";
                }

                $lines[] = '   ```';
            }

            $lines[] = '';
        }

        $lines[] = '> '.$this->automationBoundary();
        $lines[] = '';
        $lines[] = '## v1 boundaries';
        $lines[] = '';
        $lines[] = $this->v1LimitSummary();
        $lines[] = '';
        $lines[] = 'Continue with [Privacy declarations](privacy.md) and the [v1 platform data reference](data-reference.md).';

        return implode("\n", $lines)."\n";
    }
}
